package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Complete Light Theme Roles (Emerald Botanical/Jawwal Theme)
val LightPrimary = Color(0xFF0B7D4B)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFE2F6EC)
val LightOnPrimaryContainer = Color(0xFF002106)
val LightSecondary = Color(0xFF526350)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD5E8D0)
val LightOnSecondaryContainer = Color(0xFF101F10)
val LightTertiary = Color(0xFF39656B)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFBCEBF2)
val LightOnTertiaryContainer = Color(0xFF001F23)
val LightBackground = Color(0xFFF8FAF7)
val LightOnBackground = Color(0xFF191D18)
val LightSurface = Color(0xFFF8FAF7)
val LightOnSurface = Color(0xFF191D18)
val LightSurfaceVariant = Color(0xFFDDE4DC)
val LightOnSurfaceVariant = Color(0xFF414942)
val LightOutline = Color(0xFF717972)
val LightOutlineVariant = Color(0xFFC1C9C0)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)

// Complete Dark Theme Roles (Premium Minimalist Dark Mode)
val DarkPrimary = Color(0xFF28BA76)
val DarkOnPrimary = Color(0xFF00390F)
val DarkPrimaryContainer = Color(0xFF163E2B)
val DarkOnPrimaryContainer = Color(0xFFB7F1B3)
val DarkSecondary = Color(0xFFB9CCB5)
val DarkOnSecondary = Color(0xFF253424)
val DarkSecondaryContainer = Color(0xFF3B4B39)
val DarkOnSecondaryContainer = Color(0xFFD5E8D0)
val DarkTertiary = Color(0xFFA1CED6)
val DarkOnTertiary = Color(0xFF00363C)
val DarkTertiaryContainer = Color(0xFF1F4D53)
val DarkOnTertiaryContainer = Color(0xFFBCEBF2)
val DarkBackground = Color(0xFF111411)
val DarkOnBackground = Color(0xFFE1E4DF)
val DarkSurface = Color(0xFF111411)
val DarkOnSurface = Color(0xFFE1E4DF)
val DarkSurfaceVariant = Color(0xFF414942)
val DarkOnSurfaceVariant = Color(0xFFC1C9C0)
val DarkOutline = Color(0xFF8B938B)
val DarkOutlineVariant = Color(0xFF414942)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)

// Surface Container Tokens for custom elevation layouts
val LightSurfaceContainer = Color.White
val LightSurfaceContainerHigh = Color(0xFFF5F8F5)
val LightSurfaceContainerLow = Color(0xFFF8FAF7)

val DarkSurfaceContainer = Color(0xFF1C241E)
val DarkSurfaceContainerHigh = Color(0xFF282B27)
val DarkSurfaceContainerLow = Color(0xFF191D19)
